# Real data

In [1]:
import sys
import pandas as pd

from pathlib import Path

project_root = Path.cwd()
while project_root != project_root.parent and not (project_root / "src").exists():
    project_root = project_root.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.simulation.validation import plot_market_plotly

In [4]:
df = pd.read_csv("../data/processed/real_processed_18.csv")
df.head()

,Window,Name,Price 1,Price 2,Price 3,Price 4,Price 5,Price 6,Price 7,Price 8,...,CoV_change,zero_change_fraction,AR_1,AR_2,kurtosis_change,max_abs_ret,pos_vol,neg_vol,level_vol,price_range
0,156,All Commodity Price Index,4.176713,4.251740,4.186328,4.125281,4.144148,4.164926,4.148282,4.165636,...,3.279818,0.058824,-0.098199,-0.258803,0.459396,0.075027,0.020212,0.028582,0.080836,0.252652
1,157,All Commodity Price Index,4.251740,4.186328,4.125281,4.144148,4.164926,4.148282,4.165636,4.166258,...,4.275221,0.058824,0.197604,0.102937,0.760630,0.065411,0.014549,0.028582,0.086444,0.253717
2,158,All Commodity Price Index,4.186328,4.125281,4.144148,4.164926,4.148282,4.165636,4.166258,4.211809,...,2.172046,0.058824,-0.334841,0.152696,2.015335,0.061048,0.014385,0.024192,0.093256,0.266986
3,159,All Commodity Price Index,4.125281,4.144148,4.164926,4.148282,4.165636,4.166258,4.211809,4.210375,...,1.244771,0.058824,-0.416889,0.259892,-1.005141,0.045551,0.014385,0.007829,0.097145,0.266986
4,160,All Commodity Price Index,4.144148,4.164926,4.148282,4.165636,4.166258,4.211809,4.210375,4.255512,...,1.248881,0.058824,-0.464463,0.219103,-0.385620,0.069431,0.018982,0.007829,0.101128,0.315698

In [5]:
FEATURES_5 = ["volatility", "zero_change_fraction", "max_abs_ret", "AR_1", "price_range"]

In [6]:
print(df[FEATURES_5].isna().mean())

volatility              0.000000
zero_change_fraction    0.000000
max_abs_ret             0.000000
AR_1                    0.003975
price_range             0.000000
dtype: float64

In [7]:
df[FEATURES_5].describe()

,volatility,zero_change_fraction,max_abs_ret,AR_1,price_range
count,36984.000000,36984.000000,36984.000000,36837.000000,36984.000000
mean,0.067321,0.069140,0.164312,0.141789,0.412895
std,0.079238,0.166378,0.222546,0.291262,0.411706
min,0.000000,0.000000,0.000000,-0.999857,0.000000
25%,0.028198,0.000000,0.065624,-0.055612,0.170312
50%,0.046556,0.000000,0.111900,0.142953,0.298568
75%,0.074793,0.058824,0.182320,0.341827,0.518220
max,2.109981,1.000000,7.712043,0.995652,9.973458